language: node_js
services: docker
node_js: 6.10

env:
  global:

    - AWS_ACCESS_KEY_ID=AKIAISZAI76VEQ4XD6IQ
    - SNS_QUEUE=arn:aws:sns:ap-southeast-2:873114526714:location-events-queue-dev

    # AWS_SECRET_ACCESS_KEY
    - secure: gyOScLiZiGGI9jaYbz6xNI006xEprIz5em7Qhc1KmolJiY9mFfcVR0L1u4qtKJ95ucLIIJYqyDWCx9WGQdQbnnVuK6dAv7chmRIBnqwvlGEGHa+s/AV12JLt9OvV9OqohXEp8GVL4kQ5g9cCLjdRLoHxCnO/DvaHBP4PgaFAj4GpicfLnVx+/sbilzzrs9oFNfPkffVHPMtDGJFnCy5K4nYicsefsdFUSJNj6Uz2NVsqtR5MFkixQ/Sopexs1C0z8wNunsh4ZyWRISdzbt0/WReYAWhchUZ/M0u8IyTK3M5GkCzypg3SEjmlBlNJfjRL6vw2k8Z8Pw5HntM4WuOrLIPjyPC5mt0MGZzHvANKhFNXBiU3dpx3zmsLj2oY/c8qWPnNyforV2AdcJeZD8rW5PNBoaDMhEX2YoSZuTQrQeCyY3W4s3xCTnxOdlDIAk+Zr2BdViBztOuupF48gqjWPb416etd28/0X/XWCHwjzXfCIsRrN4MWGo5ffpAhgcEq45ImQDJvcf0IX/raHKMXuqnx5wdwcN7GfxSKvxK0Lf6MuN2MNQqvV7qz2T32XRwzplAdLeKxJ/FhpD/WA4s9Zn6FtdjZbXQifhVfwGMHVa73SwiJoWmykcB1aUUoKcJ0HEUylpWmprDgvy4prm73JMOL+LvQ1iHnNR7CFC4S3LE=

install: true
script: yarn test
before_deploy: rm -rf tests package.json *.md

deploy:

  - provider: lambda
    publish: true
    function_name: proximityEventsWebhookParser
    region: ap-southeast-2
    role: arn:aws:iam::873114526714:role/genericLambdaRole
    description: Parses and queues webhook events sent by the Proximity Events iPhone app.
    runtime: nodejs6.10
    handler_name: handler
    access_key_id: AKIAISZAI76VEQ4XD6IQ
    secret_access_key:
      secure: MCV4yKe+HQ2F3J53JLSbcL2nI04NUmlDAa5Yc0/ERAmJGMGBGo85hBw7TelKVvsxM8vP3B0vExZTQ+Awlg7kep07hryaTLgKY6kJd01sgndmOczjNksxxqEoqVjR6xFD+Pll5k0HleZPmuzh3rr/FI6tG26i2UlvI+lhhvO3XQWTp1xX47bi4jhgnbK3AT+Q8UgzPUu3RD1mS87t/tFJ2dlzSFuS2SB5b1v4i6KJne9qXhf75lRe8AeMq/qkAxTWBgBqUPz2me9o+Auub2WHrQh9Hb38rNyucty5IltK+erwxnge9WEEDBXurwv3Is6CawL5QMgyic/4QfJ1iMrRgpL+o7RkR+RLWmgo+Rq/3ym9HYYMP1EEcuRUEzHQIu33ZFTaSWct5dDmR3MHLT3NVFT09YmfggoNkp/Fk0bEBKnH7mvEy8zWsTZLTz+Hahiq8J577DDSTu/9bqk45WVq/JwjKZen6egnw4h87WI4QAgee6lXEqArcP5a0to254+Yibwbq663hj6gD00GcBm/2Rlh14wHMxUEgj2eONpDdEjRGMN3T+VlbKvRKM7eggD6dSsA7WQBAfbrYEoEgCEE8zTT7xeiyLkMTzxeGJWPtbfMs43v5sdpkcD/SmZ+932B18HHojmvo98ykWozbI+YyaoYj0WjQWwrXj6Qh/d/yYU=
    skip_cleanup: true
    on:
      branch: master

  - provider: npm
    email: tdmalone@gmail.com
    api_key:
      secure: eZDnL1SGpt0dbOCERxIdHu4Aamyf+kslz4LdZup6bzUg6ehUrrl989z0EZWJka/tU/IXVU00lopTplk0nxgCpuwTHhaCprXRcVnXglgyPyzvSZANHc0YQrgTtEWhLWurK70gj9zzyB7K7s+sLTUrXaMfQW8js4HdhbgFLeWEPXv6M7TWarZwsI5ftYB993TiaaWnhU33Jdn++KuUwuT2FYjRexCiAs5qBwwOuuN5NOEKDt6eyCf97OItUAgEsphJYjCpKesFOZNTARWhSBrkBMZHcqvE7vE2SwJ+LI8Krfe3IbY1FpVHmy62ytbofwYXMvKca0BRx7DovK6F1uunjOxbOD1G/qqbzXU+M5FwrKipgjOMHZUgO4sOCtQBBW7IG2hlMVpuCEqtnCcmlmRQEt8oqqoeQWzld9orKIrx2hPacYRYtYhpu8id2D1OT+IVY5AIT8mmvF2VJlVxX1TFJhKZq/2rd1EbAyAC0ZmSzegwBGArYoFgP7/gN93zHHep5ijBpSEc/DqpJ+FHCW2lhrgL8ag76dHGi5170cCerzhEJKlhpJuOg3naoTHO0SUnahKInJrd/HcN/lg1DRNYZV3W4Y1leo65MtDhM/CxPf9zTWfFkOyFSEMzKbX83CkD3V9w1HVur5GO6SBXoHWkZh99aj6jYnrxJQ+bhL6+npE=
    on:
      branch: master
      tags: true

notifications:
  email: false
  slack:
    on_start: always
    rooms:
      - secure: Vy2JA/ktcFrTVRPzvyQwBh4Q65Hb6lBCbM8RMshxtdSRNSVnctRofN3BJ/QlutYV4EbsWA1jgQaSb3BH0IPF5Mg5MUkv8c1bbW+GbNzMqQG3td2CcjlYF4IVB5Zd+ONqEDQJLglF1z2kwyPh1ZmaWgSvYVc2yhrkqJl3oFdhertAM2sNF7om/KugrCQsjJm+jFhNY62P84jhed7+cmNT6xl9IMN9gZvUqssdvLubmdMTpgz9JBvbn1hAMFI3JjSaHEowAMolnE3mCSlC8aLSjfdX+lKR8vRJGXzURX74eUm7jEM0vHnwn1QrRTUZdUzUl6pP9yaPPDUHNf+Lsu/fZe/vIoQW5J31Wg9itunNF6dvUduYNnDsNWW0UqokmfUkmaHlLMf1VrAjKumahHG5eSmNkgoGaYHhygrWUD1lziwjGkXf9YnCV4lgdoU5m9c+h6NeXSEI8E7IMMZLr0cwAFkqW68PQPeEcus9xWdhBMLE5DZn85EIG78Qj3qF4HliJjtuDhQPr1PsaDoun/0s3MN3cKOnDh7iuKrJU51yXnrDvW0HXzZhhc78R/mU9V0n0Isx9hizuur9eXOcbVOFG5zOaIMlFNb0pEAIkw5kaIvgLRlUf8HUm00QVIevqx17idrTkWBWd5Znan/NmVym+wMD1IjhVvYV6aI7ZRIT5vY=
