language: node_js
services: docker
node_js: 6.10
install: true
script: yarn test
before_deploy: rm -rf tests package.json *.md

deploy:

  on:
    branch: master
  skip_cleanup: true

  # TODO: Also publish to npm.

  # @see https://docs.travis-ci.com/user/deployment/lambda/
  provider: lambda
  publish: true
  function_name: "proximityEventsWebhookParser"
  region: "ap-southeast-2"
  role: "arn:aws:iam::873114526714:role/genericLambdaRole"
  description: "Parses and queues webhook events sent by the Proximity Events iPhone app."
  runtime: "nodejs6.10"
  handler_name: "handler"
  access_key_id: "AKIAJVWRHTUGC7RFRHXQ"
  secret_access_key:
    secure: "hcmnv7X2MoLLiEvYBYFcZk6b3Km8d/IdrcyU4Q2N6ylKB81f3YVzU4xGdv+s2PBiZTtdSqjpO6uno7FBquBJ5k4TVglyba6reOWDCUkCxmv6oh+G7yGJ5p0md4h7lkCT3BuJJ5M936spHQzQMmCWhk27bjXYBMGgTsaiW+JrpIS2Aw2YEjpFcxkcbaVoFEJoY4KCKyWp0PQ8qyoBTR+K63ArO6ZpvJs6cUWuAjpWa2321WrpcetHD9c4Unr7r1oHpq6M7a7VYPirJbKVkj6dqObiWSevxZ1nMNDiqM0vb/nXC8lCQxGtIt7fteyTpV3PxPno8AFUtiM955WiwelSFL/vYVrpr9V+Bitrp2be6Z7OknHjzH7AP7Ej/5k16kTHr9fKdeO1MU4k837tCFlzFwda3biUYupWxmQOhhLGP/zWrdfIe4q6UzQjyOEBhzoFVnh0NMI7AC0h7a0k/AsqobhwK4FuJJCE+8wvzrKFB0Bub7SIspD7NhPx2Wn0oU/kPEIyDTpeY4TllvzM9SDXutYIq/xZjt8+1BsUft8OKm/XzGvdbgK3292OmTDTlDMk0VHxAhkO+HrYEliE03E1WemBmBQyUhd+xoU1bAhAXPHoqBoa8tA3p1BKNvdz+Ww1tAckjunO6g4UnhRj4IV2kNu0I1w8wLnXZ3Frdd8o5fw="

notifications:
  email: false
  slack:
    on_start: always
    rooms:
      - secure: "Vy2JA/ktcFrTVRPzvyQwBh4Q65Hb6lBCbM8RMshxtdSRNSVnctRofN3BJ/QlutYV4EbsWA1jgQaSb3BH0IPF5Mg5MUkv8c1bbW+GbNzMqQG3td2CcjlYF4IVB5Zd+ONqEDQJLglF1z2kwyPh1ZmaWgSvYVc2yhrkqJl3oFdhertAM2sNF7om/KugrCQsjJm+jFhNY62P84jhed7+cmNT6xl9IMN9gZvUqssdvLubmdMTpgz9JBvbn1hAMFI3JjSaHEowAMolnE3mCSlC8aLSjfdX+lKR8vRJGXzURX74eUm7jEM0vHnwn1QrRTUZdUzUl6pP9yaPPDUHNf+Lsu/fZe/vIoQW5J31Wg9itunNF6dvUduYNnDsNWW0UqokmfUkmaHlLMf1VrAjKumahHG5eSmNkgoGaYHhygrWUD1lziwjGkXf9YnCV4lgdoU5m9c+h6NeXSEI8E7IMMZLr0cwAFkqW68PQPeEcus9xWdhBMLE5DZn85EIG78Qj3qF4HliJjtuDhQPr1PsaDoun/0s3MN3cKOnDh7iuKrJU51yXnrDvW0HXzZhhc78R/mU9V0n0Isx9hizuur9eXOcbVOFG5zOaIMlFNb0pEAIkw5kaIvgLRlUf8HUm00QVIevqx17idrTkWBWd5Znan/NmVym+wMD1IjhVvYV6aI7ZRIT5vY="